### ISSUE TITLE
run not working

### ISSUE THREAD

**Issue by gj12** [novnc/websockify#264]
Hi,

I upgraded websockify to master from github and now I get the following error:

```
Traceback (most recent call last):
  File "./run", line 5, in <module>
    websockify.websocketproxy.websockify_init()
  File "/root/websockify/websockify/websocketproxy.py", line 536, in websockify_init
    server = WebSocketProxy(**opts.__dict__)
  File "/root/websockify/websockify/websocketproxy.py", line 277, in __init__
    websockifyserver.WebSockifyServer.__init__(self, RequestHandlerClass, *args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'auto_pong'
```

My start command is:
 ` /usr/bin/python ./run 443 --web=web -D --ssl-only --cert=cert.pem --key=ssl.key --wrap-mode=ignore -- vncserver2 -depth 16 -geometry 1600x900 :2`

My System: Linux x64 with Python 3.6.0

**Comment by tabka** [comment]
I have the same issue!! @gj12 did you find a solution?

**Comment by jankeromnes** [comment]
FYI this seems to break noVNC: https://github.com/novnc/noVNC/issues/769

**Comment by jankeromnes** [comment]
I used `git bisect` and found out that this bug was introduced by commit 8a697622495fd319582cd1c604e7eb2cc0ac0ef6.

Additionally, the previous commit 4099949984eb80ef33c2d0dd216991124975a5d2 doesn't have this problem, but seems to break WebSocket connection, so the last good commit is the one before that, 56a4ccbf74be59484fad9878ea6c155c3edc0ff9.

**Comment by CendioOssman** [comment]
Crap. I missed one instance of `auto_pong` since it used `-` instead of `-`. Should be fixed in 94783ea0cd3a374410be61283f538c93cad1650e.
